# Generated by Django 3.0.2 on 2020-02-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterPrinterDoc',
            fields=[
                ('rp_doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('doc', models.TextField()),
            ],
        ),
    ]
