# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\register_printer_gui\mainwindow.ui',
# licensing of '..\register_printer_gui\mainwindow.ui' applies.
#
# Created: Sun Nov 10 16:08:18 2019
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(491, 313)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.frame = QtWidgets.QFrame(self.splitter)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.excel_path_editor = QtWidgets.QLineEdit(self.frame)
        self.excel_path_editor.setObjectName("excel_path_editor")
        self.gridLayout.addWidget(self.excel_path_editor, 1, 1, 1, 1)
        self.output_path_editor = QtWidgets.QLineEdit(self.frame)
        self.output_path_editor.setObjectName("output_path_editor")
        self.gridLayout.addWidget(self.output_path_editor, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.config_file_editor = QtWidgets.QLineEdit(self.frame)
        self.config_file_editor.setObjectName("config_file_editor")
        self.gridLayout.addWidget(self.config_file_editor, 0, 1, 1, 1)
        self.config_file_button = QtWidgets.QToolButton(self.frame)
        self.config_file_button.setObjectName("config_file_button")
        self.gridLayout.addWidget(self.config_file_button, 0, 2, 1, 1)
        self.excel_path_button = QtWidgets.QToolButton(self.frame)
        self.excel_path_button.setObjectName("excel_path_button")
        self.gridLayout.addWidget(self.excel_path_button, 1, 2, 1, 1)
        self.output_path_button = QtWidgets.QToolButton(self.frame)
        self.output_path_button.setObjectName("output_path_button")
        self.gridLayout.addWidget(self.output_path_button, 2, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_3.addWidget(self.checkBox_4)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_3.addWidget(self.checkBox_3)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_3.addWidget(self.checkBox_2)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_3.addWidget(self.checkBox)
        self.gridLayout.addWidget(self.groupBox, 3, 0, 1, 3)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(200, -1, 200, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_4.addWidget(self.pushButton)
        self.verticalLayout_2.addWidget(self.widget)
        self.logging_editor = QtWidgets.QTextEdit(self.splitter)
        self.logging_editor.setReadOnly(True)
        self.logging_editor.setObjectName("logging_editor")
        self.verticalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "RegisterPrinter GUI", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Config file:", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Output path:", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Excel path:", None, -1))
        self.config_file_button.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.excel_path_button.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.output_path_button.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Generate options:", None, -1))
        self.checkBox_4.setText(QtWidgets.QApplication.translate("MainWindow", "Generate register documents.", None, -1))
        self.checkBox_3.setText(QtWidgets.QApplication.translate("MainWindow", "Generate register C header files.", None, -1))
        self.checkBox_2.setText(QtWidgets.QApplication.translate("MainWindow", "Generate register UVM models.", None, -1))
        self.checkBox.setText(QtWidgets.QApplication.translate("MainWindow", "Generate register RTL modudles.", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Generate", None, -1))

